version: '3.7'

services:
  api:
    container_name: boilerplate-api
    build:
      context: .
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
    command: yarn start:dev
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - redis
      - postgres
  redis:
    image : redis:6
    container_name: boilerplate-redis
    command:
      - "redis-server"
      - "--requirepass ${REDIS_PASSWORD}"
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
  postgres:
    container_name: boilerplate-postgres
    image: postgres:13
    networks:
      - app-network
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  app-network:
volumes:
  pgdata: {}


